elink/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from firstapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^host/$', views.special, name='host'),

    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^create/$', views.C_Rooms, name='create'),
    url(r'^join/$', views.J_Rooms, name='join'),

    url(r'^firstapp/',include('firstapp.urls')),
]

firstapp/urls.py
from django.conf.urls import url
from firstapp import views

app_name = 'firstapp'

urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^user_login/$', views.user_login, name='user_login'),

]

firstapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #age
    age = models.IntegerField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

class Client(models.Model):
    user_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.user_name



class Created_Rooms(models.Model):
    # User= settings.AUTH_USER_MODEL
    user = models.OneToOneField(User)

    # user= models.ForeignKey(User, null=True)
    name= models.CharField(max_length=500)

class Joined_Rooms(models.Model):
    # User= settings.AUTH_USER_MODEL
    # user= models.ForeignKey(User, null=True)
    user = models.OneToOneField(User)
    name= models.CharField(max_length=500)
    def __str__(self):
        return self.user.username

firstapp/forms.py
from django import forms
from django.contrib.auth.models import User
from firstapp.models import UserProfileInfo
from .models import Client,Created_Rooms,Joined_Rooms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('age','profile_pic')



class clientForm(forms.ModelForm ):
    class Meta:
        model= Client
        fields = '__all__'

class Created_RoomsForm(forms.ModelForm ):
    class Meta:
        model= Created_Rooms
        fields = '__all__'

class Joined_RoomsForm(forms.ModelForm ):
    class Meta:
        model= Joined_Rooms
        fields = '__all__'

firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from firstapp.models import Client,Created_Rooms,Joined_Rooms
from firstapp.forms import clientForm,Created_RoomsForm,Joined_RoomsForm
from firstapp.forms import UserForm
# from django.template import RequestContext
from django.contrib.auth import login,logout,authenticate
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


from firstapp.forms import UserProfileInfoForm

# Create your views here.
#
# from django.contrib.auth import login, authenticate
# from django.contrib.auth.forms import UserCreationForm
# from django.shortcuts import render, redirect
#
# def signup(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('index')
#     else:
#         form = UserCreationForm()
#     return render(request, 'signup.html', {'form': form})

#@login_required
def index(request):
    # client_Form = clientForm(request.POST or None)
    # if client_Form.is_valid():
    #     instance = client_Form.save()
    # my_dict = {'insert_me':"Hello i am view.py", 'form':client_Form}
    # print current_user.id
    # if request.user.is_authenticated():
    #     current_user = request.user.password
    # else:
    #     current_user =''
    return render(request,'firstapp/index.html')

def signup(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data= request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile.pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'firstapp/signup.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login and failed!")
            # print("Username {} and password {}".formate(username,password))
            # return HttpResponse("invalid login detaion supplied!")
            # strng="Incalid user name or Password"
            # invalid_dic = {'inval':strng}
            return render(request,'firstapp/login.html', {})


    else:
        return render(request,'firstapp/login.html', {})

#logout

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def special(request):
    # client_Form = clientForm(request.POST or None)
    # if client_Form.is_valid():
    #     instance = client_Form.save()
    # my_dict = {'insert_me':"Hello i am view.py", 'form':client_Form}
    return render(request,'firstapp/special.html')



@login_required
def C_Rooms(request):

    c_rooms= Created_Rooms.objects.all()
    # rname=c_rooms
    form= Created_RoomsForm(request.POST or None)
    if form.is_valid():
        fs= form.save(commit=False)
        fs.user= request.user
        fs.save()

    context= {'form': form,
              'c_rooms': c_rooms,
              }

    return render(request, 'firstapp/createdRooms.html', context)


@login_required
def J_Rooms(request):

    j_rooms= Joined_Rooms.objects.all()
    # rname=c_rooms
    form= Joined_RoomsForm(request.POST or None)
    if form.is_valid():
        fs= form.save(commit=False)
        fs.user= request.user
        fs.save()

    context= {'form': form,
              'j_rooms': j_rooms,
              }

    return render(request, 'firstapp/joinedrooms.html', context)

templates/firstapp/base.html
<!DOCTYPE html>
<!-- {% load staticfiles %} -->
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>RTC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <link rel="shortcut icon" href="logo.png">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href= "{% static "css/stylesheet.css" %}"/>
  <script src="{% static "js/menu.js" %}"></script>
</head>
<body>
  <header class="jumbotron">

<!-- <nav class="navbar navbar-default navar-static-top">
  <ul class="nav navbar-nav">
    <li>    <a  href="{% url 'firstapp:index' %}"><img src="{% static "images/logo.png" %}" alt="RTCMultiConnection"></a></li>

  </ul>
</nav> -->

  <!-- <div class="jumbotron"> -->
    <!--<img src="{% static "images/logo.png" %}" alt="RTCMultiConnection"> -->
    <a class="logo" href="{% url 'firstapp:index' %}">RTC</a>
    <a href="{% url 'firstapp:index' %}" class="menu-explorer">Menu<img src="{% static "images/menu-icon.png" %}" alt="Menu"></a>
    <nav>

      {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li>
          <a href="{% url 'firstapp:user_login' %}">Login</a>
        </li>
      {% endif %}

      {% if not user.is_authenticated %}
      <li>
        <a href="{% url 'firstapp:signup' %}">Registration</a>
      </li>
      {% endif %}

      <li>
        <a href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li>
        <a href="{% url 'host' %}">Host/Join Room</a>
      </li>
      <!-- <li>
        <a href="{% url 'join' %}">Join Room</a>
      </li>
      <li>
        <a href="{% url 'create' %}">Create Room</a>
      </li> -->
    </nav>
    <!-- </div> -->
  </header>


<!-- <div class="jumbotron"> -->

  <h1 class="jumbotron">
    Real Time Communication
  </h1>

<!-- </div> -->

{% block body_block %}

{% endblock %}
</body>
</html>

templates/firstapp/createdRooms.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div >
  <form class="jumbotron" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <p >{{ c_rooms }}</p>
    <input type="submit" name="" value="creatrooms">

  </form>
</div>

{% endblock %}

templates/firstapp/index.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div >
  <h1 class="jumbotron">Index page </h1>
  <p>{{ name }}</p>
</div>

{% endblock %}

templates/firstapp/joinedrooms.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div >
  <form class="jumbotron" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <p >{{ j_rooms }}</p>
    <input type="submit" name="" value="creatrooms">

  </form>
</div>

{% endblock %}

templates/firstapp/login.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}

{% block body_block %}


<div class="jumbotron">
  <h1>Please Login! </h1>
  <form action="{% url 'firstapp:user_login' %}" method="post">
    {% csrf_token %}
    {{ invalid_dic }}
    <label for="username" >Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>


</div>
{% endblock %}

templates/firstapp/signup.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering! </h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>


    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <button type="submit" value="Register">Sign up</button>
    </form>
  {% endif %}
</div>

{% endblock %}

templates/firstapp/special.html
{% extends "firstapp/base.html" %}
{% load staticfiles %}

{% block body_block %}

<!-- <div class="jumbotron">

</div> -->


      <section class="make-center">
        <!-- <input type="text" name="user_name" maxlength="264" required id="id_user_name" />
        <form method="post">
          {%csrf_token%}
          {{form.as_p}}
          <input type="submit" value="submit">
        </form> -->
    <!-- <form method="post">
        {%csrf_token%}
        <input type="text" name="user_name"  id="id_user_name" size=20 />
        <input type="submit" value="open room"></input>
    </form> -->
            <input type="text" id="room-id" value="abcdef" autocorrect=off autocapitalize=off size=20>
            <button id="open-room">Open Room</button>
            <button id="join-room">Join Room</button>
            <button id="open-or-join-room">Auto Open Or Join Room</button>
            <br><br>
            <input type="text" id="input-text-chat" placeholder="Enter Text Chat" disabled>
            <button id="share-file" disabled>Share File</button>
            <br><br>
            <button style="margin-bottom: 200px" id="btn-leave-room" disabled>Leave /or close the room</button>

            <div id="room-urls" style="text-align: center;display: none;background: #F1EDED;margin: 15px -10px;border: 1px solid rgb(189, 189, 189);border-left: 0;border-right: 0;"></div>

            <div id="chat-container">
                <div id="file-container"></div>
                <div class="chat-output"></div>
            </div>
            <div id="videos-container"></div>
      </section>


    <script type="text/javascript" src="{% static "js/RTCMultiConnection.min.js" %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/adapter.js' %}"></script> -->
    <script type="text/javascript" src="{% static "js/socket.io.js" %}"></script>
    <script type="text/javascript" src="{% static "js/adapter.js" %}"></script>

    <!-- <script src="{% static 'js/adapter.js' %}" type="text/javascript"></script> -->
    <!-- <script src="{% static 'js/socket.io.js' %}" type="text/javascript"></script> -->

    <!-- custom layout for HTML5 audio/video elements -->
    <link rel="stylesheet" href= "{% static "css/getHTMLMediaElement.css" %}"/>
    <script type="text/javascript" src="{% static "js/getHTMLMediaElement.js" %}"></script>
    <script src="{% static 'js/FileBufferReader.js' %}"></script>

    <script>
    window.enableAdapter = true; // enable adapter.js

    // ......................................................
    // .......................UI Code........................
    // ......................................................
    document.getElementById('open-room').onclick = function() {
        disableInputButtons();
        connection.open(document.getElementById('room-id').value, function() {
            showRoomURL(connection.sessionid);
        });
    };

    document.getElementById('join-room').onclick = function() {
        disableInputButtons();
        connection.join(document.getElementById('room-id').value);
    };

    document.getElementById('open-or-join-room').onclick = function() {
        disableInputButtons();
        connection.openOrJoin(document.getElementById('room-id').value, function(isRoomExists, roomid) {
            if (!isRoomExists) {
                showRoomURL(roomid);
            }
        });
    };

    document.getElementById('btn-leave-room').onclick = function() {
        this.disabled = true;

        if (connection.isInitiator) {
            // use this method if you did NOT set "autoCloseEntireSession===true"
            // for more info: https://github.com/muaz-khan/RTCMultiConnection#closeentiresession
            connection.closeEntireSession(function() {
                document.querySelector('h1').innerHTML = 'Entire session has been closed.';
            });
        } else {
            connection.leave();
        }
    };

    // ......................................................
    // ................FileSharing/TextChat Code.............
    // ......................................................

    document.getElementById('share-file').onclick = function() {
        var fileSelector = new FileSelector();
        fileSelector.selectSingleFile(function(file) {
            connection.send(file);
        });
    };

    document.getElementById('input-text-chat').onkeyup = function(e) {
        if (e.keyCode != 13) return;

        // removing trailing/leading whitespace
        this.value = this.value.replace(/^\s+|\s+$/g, '');
        if (!this.value.length) return;

        connection.send(this.value);
        appendDIV(this.value);
        this.value = '';
    };

    var chatContainer = document.querySelector('.chat-output');

    function appendDIV(event) {
        var div = document.createElement('div');
        div.innerHTML = event.data || event;
        chatContainer.insertBefore(div, chatContainer.firstChild);
        div.tabIndex = 0;
        div.focus();

        document.getElementById('input-text-chat').focus();
    }

    // ......................................................
    // ..................RTCMultiConnection Code.............
    // ......................................................

    var connection = new RTCMultiConnection();

    // by default, socket.io server is assumed to be deployed on your own URL
    //connection.socketURL = 'https://cfclink.com/anas/test9:443/';

    // comment-out below line if you do not have your own socket.io server
     connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';

    connection.socketMessageEvent = 'audio-video-file-chat-demo';

    connection.enableFileSharing = true; // by default, it is "false".

    connection.session = {
        audio: true,
        video: true,
        data: true
    };

    connection.sdpConstraints.mandatory = {
        OfferToReceiveAudio: true,
        OfferToReceiveVideo: true
    };

    connection.videosContainer = document.getElementById('videos-container');
    connection.onstream = function(event) {
        event.mediaElement.removeAttribute('src');
        event.mediaElement.removeAttribute('srcObject');

        var video = document.createElement('video');
        video.controls = true;
        if(event.type === 'local') {
            video.muted = true;
        }
        video.srcObject = event.stream;

        var width = parseInt(connection.videosContainer.clientWidth / 2) - 20;
        var mediaElement = getHTMLMediaElement(video, {
            title: event.userid,
            buttons: ['full-screen'],
            width: width,
            showOnMouseEnter: false
        });

        connection.videosContainer.appendChild(mediaElement);

        setTimeout(function() {
            mediaElement.media.play();
        }, 5000);

        mediaElement.id = event.streamid;
    };

    connection.onstreamended = function(event) {
        var mediaElement = document.getElementById(event.streamid);
        if (mediaElement) {
            mediaElement.parentNode.removeChild(mediaElement);
        }
    };

    connection.onmessage = appendDIV;
    connection.filesContainer = document.getElementById('file-container');

    connection.onopen = function() {
        document.getElementById('share-file').disabled = false;
        document.getElementById('input-text-chat').disabled = false;
        document.getElementById('btn-leave-room').disabled = false;

        document.querySelector('h1').innerHTML = 'You are connected with: ' + connection.getAllParticipants().join(', ');
    };

    connection.onclose = function() {
        if (connection.getAllParticipants().length) {
            document.querySelector('h1').innerHTML = 'You are still connected with: ' + connection.getAllParticipants().join(', ');
        } else {
            document.querySelector('h1').innerHTML = 'Seems session has been closed or all participants left.';
        }
    };

    connection.onEntireSessionClosed = function(event) {
        document.getElementById('share-file').disabled = true;
        document.getElementById('input-text-chat').disabled = true;
        document.getElementById('btn-leave-room').disabled = true;

        document.getElementById('open-or-join-room').disabled = false;
        document.getElementById('open-room').disabled = false;
        document.getElementById('join-room').disabled = false;
        document.getElementById('room-id').disabled = false;

        connection.attachStreams.forEach(function(stream) {
            stream.stop();
        });

        // don't display alert for moderator
        if (connection.userid === event.userid) return;
        document.querySelector('h1').innerHTML = 'Entire session has been closed by the moderator: ' + event.userid;
    };

    connection.onUserIdAlreadyTaken = function(useridAlreadyTaken, yourNewUserId) {
        // seems room is already opened
        connection.join(useridAlreadyTaken);
    };

    function disableInputButtons() {
        document.getElementById('open-or-join-room').disabled = true;
        document.getElementById('open-room').disabled = true;
        document.getElementById('join-room').disabled = true;
        document.getElementById('room-id').disabled = true;
    }

    // ......................................................
    // ......................Handling Room-ID................
    // ......................................................

    function showRoomURL(roomid) {
        var roomHashURL = '#' + roomid;
        var roomQueryStringURL = '?roomid=' + roomid;

        var html = '<h2>Unique URL for your room:</h2><br>';

        html += 'Hash URL: <a href="' + roomHashURL + '" target="_blank">' + roomHashURL + '</a>';
        html += '<br>';
        html += 'QueryString URL: <a href="' + roomQueryStringURL + '" target="_blank">' + roomQueryStringURL + '</a>';

        var roomURLsDiv = document.getElementById('room-urls');
        roomURLsDiv.innerHTML = html;

        roomURLsDiv.style.display = 'block';
    }

    (function() {
        var params = {},
            r = /([^&=]+)=?([^&]*)/g;

        function d(s) {
            return decodeURIComponent(s.replace(/\+/g, ' '));
        }
        var match, search = window.location.search;
        while (match = r.exec(search.substring(1)))
            params[d(match[1])] = d(match[2]);
        window.params = params;
    })();

    var roomid = '';
    if (localStorage.getItem(connection.socketMessageEvent)) {
        roomid = localStorage.getItem(connection.socketMessageEvent);
    } else {
        roomid = connection.token();
    }
    document.getElementById('room-id').value = roomid;
    document.getElementById('room-id').onkeyup = function() {
        localStorage.setItem(connection.socketMessageEvent, this.value);
    };

    var hashString = location.hash.replace('#', '');
    if (hashString.length && hashString.indexOf('comment-') == 0) {
        hashString = '';
    }

    var roomid = params.roomid;
    if (!roomid && hashString.length) {
        roomid = hashString;
    }

    if (roomid && roomid.length) {
        document.getElementById('room-id').value = roomid;
        localStorage.setItem(connection.socketMessageEvent, roomid);

        // auto-join-room
        (function reCheckRoomPresence() {
            connection.checkPresence(roomid, function(isRoomExists) {
                if (isRoomExists) {
                    connection.join(roomid);
                    return;
                }

                setTimeout(reCheckRoomPresence, 5000);
            });
        })();

        disableInputButtons();
    }
    </script>


{% endblock %}